// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagement.Models;

namespace UserManagement.Migrations
{
    [DbContext(typeof(UserDetailContext))]
    [Migration("20201226133000_SecondCreate")]
    partial class SecondCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("UserManagement.Models.UserDetail", b =>
                {
                    b.Property<int>("UserDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("UserActive")
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("UserAddress")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserFirstName")
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("UserGender")
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("UserLastName")
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("UserPhone")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("UserDetailId");

                    b.ToTable("UserDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
